package com.softdesign.devintensive.utils;


public interface ConstantManager {
    String TAG_PREFIX="DEV";
    String COLOR_MODE_KEY="COLOR_MODE_KEY";

    String EDIT_MODE_KEY = "EDIT_MODE_KEY";

    String USER_PHONE_KEY = "USER_PHONE_KEY";
    String USER_MAIL_KEY = "USER_MAIL_KEY";
    String USER_VK_KEY = "USER_VK_KEY";
    String USER_GIT_KEY = "USER_GIT_KEY";
    String USER_BIO_KEY = "USER_BIO_KEY";
    String USER_PHOTO_KEY = "USER_PHOTO_KEY";
    String AUTH_TOKEN = "AUTH_TOKEN";
    String USER_ID_KEY = "USER_ID_KEY";

    String USER_RATING_VALUES = "USER_RATING_VALUES";
    String USER_CODE_LINES_VALUES = "USER_CODE_LINES_VALUES";
    String USER_PROJECT_VALUES = "USER_PROJECT_VALUES";
    String PARCELABLE_KEY = "PARCELABLE_KEY";

    int LOAD_PROFILE_PHOTO = 1;
    int REQUEST_CAMERA_PICTURE = 99;
    int REQUEST_GALLERY_PICTURE = 88;

    int PERMISOPN_REQUEST_SETTING_CODE = 101;
    int CAMERA_REQUEST_PERMISION_CODE = 102;

}
